language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew clean cleanBuildCache check --stacktrace --rerun-tasks"
after_success:
- tools/release/deploy_snapshot.sh
- bash <(curl -s https://codecov.io/bash)
after_script:
- tools/release/deploy_cleanup.sh
before_install:
- yes | sdkmanager "platforms;android-29"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: ogS3pHIzs5ooRJoQx0i2KWzechVInjYEKF5/Di1OpzcYl0XkgB/HiUvEAgcgxuXrrs2CS/O82P2W10ACrnM6pwIH2mjKFH6hKw2Rd3/r4fG3m1FgHiHDnwU8v8baOmH/gDsmTIUVM0LxsU7ILn1GPmEzN8aamGM/vzfeoDVkz6fLKcsxHQs7sTWskZLHiSQ75V2IxTkSie9TxVotV7NIbDfKAZX/Yjnc62njnZ+5DQ1EhNqwVXXbNVFamq9k6C7gXinaFhC2FS0DJLX1NSPTj3qd+cE9A1SKMZsz3jahYtw3xBMoVdjIPeAoQlrMNB13Ihuwz8jXoLwuTQSNckcOiw1gH01R4KgwOKiN2hiqgcDt+xo9CZ8yCNlaKndC8yal343auWoBW1ojC5tcxRUJjtY/pobByECRmIgXFkkp08yiFFt3FYEDV11HC0kL4UdlXkDRyi4+ifjppdr2dytY2BJdsAASJ++vzflkNaaA5xmKs3MfGOYT8fYbn9qcBdEt5SE7TqNO87GYD694kvxi8mpLyhq//VTSlmC/M8QHsxp0dl60MjuFHFLJ+cV4RjJBKsaezi6S0nAAky85rxGfDoVAZTASXiw/dkAwwT7Anc1bNBZ61yVGuE3bKSfJsgWTBn0u4xlqHVnvifYFkEi2A4+cFwLB0SpS2rV/yDc+OC4=
  - secure: wYCcCevCevS8h8Yz0VQDGMT9avlHM56U2+xmOBGtRYsCexT58eW9GJYSdD5FTFpkMWXOkAZNfTMun8LzT1Gdp2ODUFY3djIjeFc6pyld2Cp1kK10pBnqfErsfrJTRRmXjTRaX3ZdhrCpBASu71TTDHm0bBAgs733gTLA3y3oycXyd7jn8+7UUBTn8mclDDKYUVp8/E6gEj4xhxdwa7vy91V3XvXoYfxFbOTXlFdVFpENdo/E32JYjPPcXfRbgk5egnsHzRxiMX8tCG8MhRrWH301WjwMXAJaSuXoGvjFibiqamR86cd2ROXWr421Ku3nzn0Po6XHeYOfE1jVRt5H/Vf12pnV/VqX8K/s0k5mzTYPkyrgJWU2eaUQe8ULhhQkDalpH3BPu/Cxkf1JPE4pltQ8V+EkF1Ig76N60WOHtTc6GdxUGkMpO6eVJRlG1Q1gLkK7gs5igtbxOZyXsv1mnx+2c0fCvzGMmU4n6RTu0kgfS0vm7TY2/VYveprUzX6TGJeXgUBt/nzxwJQ6zYz6u+9lhsu3767n7nI2lpSg/minvFVhQhwzEe2TnGnpWnhwgM4Rh71Dgf9ht4HFWXdageyLG/QFSBwK/uLBaMheJCJUiBZ41gFjjzTeoJtybeZNSwFya74fIPiJlSjI4jeu40tkAxx4alX+cqEAIYjyDEI=
  - secure: Cr28Gzei4sKfcDTvfDrMWGn1kODX0WchJNgwTg/yivK3WWwFSzPqSt8Wijnj3SkNcEOCedd71yYsrmGz3wkk9LR7xEMBJWd0EcR01KoPL/oWb82/t5q2EUH07WJ7hTdYMqc9xc6iO9DPs4oRsIks5nDDpJF7qXmbVtbGU+YBIbdU0YHgjI0YzHaINmOz9lp1piGmn6SvSLyE4w5hVwZPkxyp/qq1Bk2U+YskAckQmAuBwv+lqewojd1StDo0WUkizT8A6EYWMy8T5D+UOqskcloSvb8Rwr7e7OoXw9cPw5zdscYKYlGc+XABgNfU7ahIoVuJOsN29cfalYQVlq418LH9OpEDnEUZ63sIm63v2pfLc6lflszN1Mby1IrC35OFg5Vj9AN6K1hHzeflsWKy1efm75grECZw8R97AJJu2OfO9eZc5cpsMLirH+KJnu7NpyImc1oLxDp23yn6lz9yhHKkfqrl5lJBPBOETTIxSyuGRU06Gi9CP/LqNraEyVuQEKXdv1modkjKAdxd2uHlMGXuRy5Oqf9y1In81HNlfzWw1NaKHFyDWffB9QbphWei8kkqcCaGldA55ZPptEv04RckSYAILBqKdDcCPjYTbbtdyuutr7XZLK58OdpohS9Tj3LYKk9gl+dc8BCsqmwIf+BWqwSajeDGw4H++HmLtP4=
  - secure: APYI4AbzzzFbhisKzXkz5+cNBbxTTMwCifaeBBdRfo5vu94dww0SApxEWUVsiybuQ1g4M2Ag4wTF+Hnv9de5CGUOIfKhEtwrUPpjMbv1HEm27XJ1sUD0I/XM0gBNDFrxb1xE86b0ecVSc9x1L1mV8N+rSaHHqZevdvtfqx4L6omjJ/VCCs7QLrzGFjbcqCrREf10yhmrVc7zXA+hX1jGr7aDd5sq9/2SDzNuUVycCCan7i37JMKJR3O46HeYWi72QrtcmpPG2jn+jpHZHeI9sebY5tZwkGRDPOQStIfCgyxT4Jp7dNo7qpjHB3PD19hKn0PgVdPhpsVDGPdQKRYkIIROXeWMhsUjOxNe93f1ZdM8tPqs7Nrgc+iY+hzBivuXqaXWmLrTmih3ZGk3cfcz6RPdKFD/18N68s2ZcUk9BqezZFO3EVDcniTaNjDZe0w23CiZntYMLXYgllFWS9flZQsm5H7xUGcMf2C7N4l8R1jQAexZ+BGcuFg/2jMex8GzJdQkm4/EJAsdHXh+IyfvykUr0g5lLSarGwOn1vQBzyH9LlGAnljstTZ2u91l01jSzlLGje/Epa0Ys1mi2975r421T017M0aO5oYX9WcGidpRDNMqSO+m2x1DvZDnNX7Vjmme/5aa4hXBxy+bGyDZxR0bbpkGNswwAjOpbCvWADg=
