language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew clean cleanBuildCache check --stacktrace --rerun-tasks"
after_success:
- tools/release/deploy_snapshot.sh
- bash <(curl -s https://codecov.io/bash)
after_script:
- tools/release/deploy_cleanup.sh
before_install:
- yes | sdkmanager "platforms;android-29"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: Cr28Gzei4sKfcDTvfDrMWGn1kODX0WchJNgwTg/yivK3WWwFSzPqSt8Wijnj3SkNcEOCedd71yYsrmGz3wkk9LR7xEMBJWd0EcR01KoPL/oWb82/t5q2EUH07WJ7hTdYMqc9xc6iO9DPs4oRsIks5nDDpJF7qXmbVtbGU+YBIbdU0YHgjI0YzHaINmOz9lp1piGmn6SvSLyE4w5hVwZPkxyp/qq1Bk2U+YskAckQmAuBwv+lqewojd1StDo0WUkizT8A6EYWMy8T5D+UOqskcloSvb8Rwr7e7OoXw9cPw5zdscYKYlGc+XABgNfU7ahIoVuJOsN29cfalYQVlq418LH9OpEDnEUZ63sIm63v2pfLc6lflszN1Mby1IrC35OFg5Vj9AN6K1hHzeflsWKy1efm75grECZw8R97AJJu2OfO9eZc5cpsMLirH+KJnu7NpyImc1oLxDp23yn6lz9yhHKkfqrl5lJBPBOETTIxSyuGRU06Gi9CP/LqNraEyVuQEKXdv1modkjKAdxd2uHlMGXuRy5Oqf9y1In81HNlfzWw1NaKHFyDWffB9QbphWei8kkqcCaGldA55ZPptEv04RckSYAILBqKdDcCPjYTbbtdyuutr7XZLK58OdpohS9Tj3LYKk9gl+dc8BCsqmwIf+BWqwSajeDGw4H++HmLtP4=
  - secure: APYI4AbzzzFbhisKzXkz5+cNBbxTTMwCifaeBBdRfo5vu94dww0SApxEWUVsiybuQ1g4M2Ag4wTF+Hnv9de5CGUOIfKhEtwrUPpjMbv1HEm27XJ1sUD0I/XM0gBNDFrxb1xE86b0ecVSc9x1L1mV8N+rSaHHqZevdvtfqx4L6omjJ/VCCs7QLrzGFjbcqCrREf10yhmrVc7zXA+hX1jGr7aDd5sq9/2SDzNuUVycCCan7i37JMKJR3O46HeYWi72QrtcmpPG2jn+jpHZHeI9sebY5tZwkGRDPOQStIfCgyxT4Jp7dNo7qpjHB3PD19hKn0PgVdPhpsVDGPdQKRYkIIROXeWMhsUjOxNe93f1ZdM8tPqs7Nrgc+iY+hzBivuXqaXWmLrTmih3ZGk3cfcz6RPdKFD/18N68s2ZcUk9BqezZFO3EVDcniTaNjDZe0w23CiZntYMLXYgllFWS9flZQsm5H7xUGcMf2C7N4l8R1jQAexZ+BGcuFg/2jMex8GzJdQkm4/EJAsdHXh+IyfvykUr0g5lLSarGwOn1vQBzyH9LlGAnljstTZ2u91l01jSzlLGje/Epa0Ys1mi2975r421T017M0aO5oYX9WcGidpRDNMqSO+m2x1DvZDnNX7Vjmme/5aa4hXBxy+bGyDZxR0bbpkGNswwAjOpbCvWADg=
  - secure: SUqJ/TVAVZfQ0JTE0bJ1NrQ4MX/c5FfgOgYcRTzc05hK4CVjy8h8FxotyeOqnBDsHwVg/AfmM6xIFAZ+DqOjstu9jI7diKVYSybxMf72FHjhyTdtCCggxGiJ+Qt2e3c8NKUDlpXO/dhq0W7MOWyaLXuI5txU2LX9bw2k4qS2AU7eOxTlXxZaVQNtoNFTYew62xxUiCdaaqHGtT4Zp5avEqVyD7YwYXXfZXJC4UdDhHsGUC50upnhiAsxtnwi1c4bNeZva1EtPpZI/83i9gQ1IcEriYOrjujAIHwttEUGl2U1NMKknmpD6zi1E5SZaEloM85GwZceAY6+ucd4vn9fvGu1J1dTzjqTFHZITR/62Y1uyqQk2Txvi3pXtH9xeuV/oWc+94l9C7nmDYhHgJeZNo8kCO5zdh4/+cAGKaJY/+CY2/uaeF5sv4w+H55uiD/qMbThzcCOkTk+rlT+2hljnN4cs9sr2C38dYZThETmayzdflle2y3JxX/qeKsiVw/I/R/4xv48xFhHACAOqgDe99MDs39QbO1goLznIKshsMAU0WEZ8Zu3KRIcAa3b1JOWkDeg6xZn0gDKEulBFO1MsGrLQ37XXy6wlYUKkN+arzYdxJzi6pfDDMw04kcHt8qyJxEcsAq+j4zwDSE5E1WbIqMfmhVKeQLKdlYAyZQ2zi8=
  - secure: azTCtAEvrh0ZYGSJOYvLdWL1wvHXxTfJjNI50jmGtkVkXwMmP2XEV2cKxZTdiom7eq5MjtDXIk15NnBE/YRL0LCvY9z5wc7JyXR8INish7y+/qz6UJ7Q7XtNLHq0p73wyNUIMDS+GjD+t7X1pdiybnIDK2D0SMNzGsCQ8yzt7v+wtkpddDJB5WxmODOz0F0i4HdXdDxx/eaXnJpJbjDvFkk+d25Ihv7GV/YniaebvL49nqDpVjLWsq+IT3Ag7ge8Nq1AWD9t0Cb6fsi4irp15gLlmdum8OuC9iuNNgdq+W+GlLN/OnhTZH+3Ic+z+WOp+t7abpKyT94Lh28sKIACrh+a7LY+JJT1LRiEx20w+2vjRCcl9+Aw1zivpUCiUYyGAziXoAuH+Mex4yNGnVJMJAwaKJhFmTD0AGmryaqzTKgS9i5V1sQpA2q6ZkrBbRINqz+69KL5p25bwroPzsZgR0gPdfpP7mjrThETgzztpbXedVdPZ8NGgdFZQvvyoUSPcRhtMGryqaH7AX342m+I96RHyBNqnVFJLSOMdO6q5EAS0/fal/go0jiiNgemwg2+oXAPbXhmIT1T/4062MEhLB7NRsKnOy6br+0PJuC/BbqNGjXkGs857pBcuz+0Tv65n9+I7zd1nyftdwCfc79zQeFknJzR5q03fNWVSQnqbiI=
  - secure: kY6xnMariQ/e2YrJcCQvRRHz5zPvK9jtf3K6BhNyt8m8ZZ94O8LSM7H7cDw+eOdj50DagPKRxp/Xy3YcbKO4roiUvb4/p/iqiPJGxwRzdg2r5qVeXOeSDXlkCfr68JpIcAFShSzE6Bc7Pgo9hYwodmzQCxG4bdVmqeDNQ2tlwadNgkby5aN1DO6RJwYgvDHF4WEevSlqbLmJapLwOFARs0gpv/wuXlv5N6Oinbgn64oqC1MJc8CpkR32bQA/yrYf8Tl+Jip9cY9RpQDJXCPc8gQHDhhbEq7pns+njNn5SSu+sTvDxBbnDjakaXx8ezMGklvScyznZOia/BJ+cuQs0xqY9iqLIGZKNdV009O9s5jDmiDvBbPb4wU6UcryjjM/Q+XTv1TfuXFbHytXUkYBWTgf7LmS69uTQ3+QAzG9ohmiQlBcipF0VLRV/lqNsePyIFuZ87u6pV/Vj6Lf0KWnksrj3FCcCFZFd+l726o55WDISdnicUSlZ6qgZnJX3iJnaVyjfeS//7JO1I1Q2XYJWl7UO4iJ0OTY51Jk94z7CVDsZEBWHOR0L8fjFRdBLEz+1Pchx+NRS9dPktNMFrH72iqQBBPZRClTPgmIWQUQvvyc9WajCRWiJ8FIBfnrHwMsM6Cs6KbU48eONju+Vy8aEeQ5LDzC4eWSQSJ5StZRVk8=
